In [23]:
# Importing Dependencies
import pandas as pd
import re

# **Skill Extraction**

### **Data Ingestion**

In [24]:
# Load in the Datasets
job_postings = pd.read_csv('../../../data/cleaned_job_postings.csv')
job_skills = pd.read_csv('../../../data/cleaned_job_skills.csv')

In [25]:
job_postings

,job_link,last_processed_time,job_title,company,City,State,job_classification,job_keyword,seniority_level,seniority_level_keyword
0,https://www.linkedin.com/jobs/view/senior-mach...,2024-01-21 08:08:48.031964+00,Senior Machine Learning Engineer,Jobs for Humanity,New Haven,CT,Machine Learning Engineer,Machine Learning Engineer,Senior-Level,Senior
1,https://www.linkedin.com/jobs/view/principal-s...,2024-01-20 04:02:12.331406+00,"Principal Software Engineer, ML Accelerators",Aurora,San Francisco,CA,Software & Platform Engineering,Software Engineer,Principal / Staff-Level,Principal
2,https://www.linkedin.com/jobs/view/senior-etl-...,2024-01-21 08:08:31.941595+00,Senior ETL Data Warehouse Specialist,Adame Services LLC,New York,NY,Data Modeling & Warehousing,Data Warehouse,Senior-Level,Senior
3,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:30:55.796572+00,Senior Data Warehouse Developer / Architect,Morph Enterprise,Harrisburg,PA,Data Modeling & Warehousing,Data Warehouse,Senior-Level,Senior
4,https://www.linkedin.com/jobs/view/lead-data-e...,2024-01-21 08:08:58.312124+00,Lead Data Engineer,Dice,Plano,TX,Data Engineer,Lead Data Engineer,Lead,Lead
...,...,...,...,...,...,...,...,...,...,...
5649,https://www.linkedin.com/jobs/view/senior-data...,2024-01-21 07:11:08.769739+00,Senior Data Scientist - Statistics,United Airlines,Chicago,IL,Data Scientist,Data Scientist,Senior-Level,Senior
5650,https://www.linkedin.com/jobs/view/data-archit...,2024-01-21 08:08:07.523737+00,Data Architect,General Dynamics Information Technology,St Louis,MO,Data Architect,Data Architect,Senior-Level,unclassified
5651,https://www.linkedin.com/jobs/view/corporate-a...,2024-01-19 15:10:41.177008+00,Corporate AML Alert Investigation Specialist,"Glacier Bancorp, Inc.",Kalispell,MT,Risk & Compliance Analytics,Aml,Senior-Level,Specialist
5652,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:20:19.036168+00,Senior Data Scientist,Highnote,San Francisco,CA,Data Scientist,Data Scientist,Senior-Level,Senior
5653,https://www.linkedin.com/jobs/view/senior-data...,2024-01-19 23:25:28.107523+00,Senior Data Engineer,CompSource Mutual Insurance Company,Oklahoma City,OK,Data Engineer,Senior Data Engineer,Senior-Level,Senior

### **Merge the Data**

In [26]:
# Merge left on job_postings and job_skills on the 'job_link' column
merged_data = job_postings.merge(job_skills, on='job_link', how='left')

# Drop the 'job_link' column
merged_data = merged_data.drop(columns=['job_link'])

# Display data head
merged_data.head()

,last_processed_time,job_title,company,City,State,job_classification,job_keyword,seniority_level,seniority_level_keyword,job_skills
0,2024-01-21 08:08:48.031964+00,Senior Machine Learning Engineer,Jobs for Humanity,New Haven,CT,Machine Learning Engineer,Machine Learning Engineer,Senior-Level,Senior,"Machine Learning, Programming, Python, Scala, ..."
1,2024-01-20 04:02:12.331406+00,"Principal Software Engineer, ML Accelerators",Aurora,San Francisco,CA,Software & Platform Engineering,Software Engineer,Principal / Staff-Level,Principal,"C++, Python, PyTorch, TensorFlow, MXNet, CUDA,..."
2,2024-01-21 08:08:31.941595+00,Senior ETL Data Warehouse Specialist,Adame Services LLC,New York,NY,Data Modeling & Warehousing,Data Warehouse,Senior-Level,Senior,"ETL, Data Integration, Data Transformation, Da..."
3,2024-01-20 15:30:55.796572+00,Senior Data Warehouse Developer / Architect,Morph Enterprise,Harrisburg,PA,Data Modeling & Warehousing,Data Warehouse,Senior-Level,Senior,"Data Lakes, Data Bricks, Azure Data Factory Pi..."
4,2024-01-21 08:08:58.312124+00,Lead Data Engineer,Dice,Plano,TX,Data Engineer,Lead Data Engineer,Lead,Lead,"Java, Scala, Python, RDBMS, NoSQL, Redshift, S..."

### **Split the job_skills column into a list of skills**

In [27]:
# Split the job_skills column into a list of skills
merged_data['job_skills'] = merged_data['job_skills'].str.split(', ')

# Display data head
merged_data.head()

,last_processed_time,job_title,company,City,State,job_classification,job_keyword,seniority_level,seniority_level_keyword,job_skills
0,2024-01-21 08:08:48.031964+00,Senior Machine Learning Engineer,Jobs for Humanity,New Haven,CT,Machine Learning Engineer,Machine Learning Engineer,Senior-Level,Senior,"[Machine Learning, Programming, Python, Scala,..."
1,2024-01-20 04:02:12.331406+00,"Principal Software Engineer, ML Accelerators",Aurora,San Francisco,CA,Software & Platform Engineering,Software Engineer,Principal / Staff-Level,Principal,"[C++, Python, PyTorch, TensorFlow, MXNet, CUDA..."
2,2024-01-21 08:08:31.941595+00,Senior ETL Data Warehouse Specialist,Adame Services LLC,New York,NY,Data Modeling & Warehousing,Data Warehouse,Senior-Level,Senior,"[ETL, Data Integration, Data Transformation, D..."
3,2024-01-20 15:30:55.796572+00,Senior Data Warehouse Developer / Architect,Morph Enterprise,Harrisburg,PA,Data Modeling & Warehousing,Data Warehouse,Senior-Level,Senior,"[Data Lakes, Data Bricks, Azure Data Factory P..."
4,2024-01-21 08:08:58.312124+00,Lead Data Engineer,Dice,Plano,TX,Data Engineer,Lead Data Engineer,Lead,Lead,"[Java, Scala, Python, RDBMS, NoSQL, Redshift, ..."

### **Explode the Job_Skills Column and Remove any Null or Empty**

In [28]:
# Explode the Split job_skills
skill_breakdown = merged_data.explode('job_skills')

# Remove any Null or Empty Skills
skill_breakdown = skill_breakdown.dropna(subset=['job_skills'])
skill_breakdown = skill_breakdown[skill_breakdown['job_skills'] != '']

# Display the first 10 rows of the skill_breakdown dataframe
skill_breakdown.head()

,last_processed_time,job_title,company,City,State,job_classification,job_keyword,seniority_level,seniority_level_keyword,job_skills
0,2024-01-21 08:08:48.031964+00,Senior Machine Learning Engineer,Jobs for Humanity,New Haven,CT,Machine Learning Engineer,Machine Learning Engineer,Senior-Level,Senior,Machine Learning
0,2024-01-21 08:08:48.031964+00,Senior Machine Learning Engineer,Jobs for Humanity,New Haven,CT,Machine Learning Engineer,Machine Learning Engineer,Senior-Level,Senior,Programming
0,2024-01-21 08:08:48.031964+00,Senior Machine Learning Engineer,Jobs for Humanity,New Haven,CT,Machine Learning Engineer,Machine Learning Engineer,Senior-Level,Senior,Python
0,2024-01-21 08:08:48.031964+00,Senior Machine Learning Engineer,Jobs for Humanity,New Haven,CT,Machine Learning Engineer,Machine Learning Engineer,Senior-Level,Senior,Scala
0,2024-01-21 08:08:48.031964+00,Senior Machine Learning Engineer,Jobs for Humanity,New Haven,CT,Machine Learning Engineer,Machine Learning Engineer,Senior-Level,Senior,Java

### **Create skill_counts_df and Group by job_classification**

In [29]:
# Group by job_classification and count the number of skills
skill_counts_df = skill_breakdown.groupby(['job_classification', 'job_skills']).size().reset_index(name='count')

# Sort values by job_classification and count in descending order
skill_counts_df = skill_counts_df.sort_values(['job_classification', 'count'], ascending=[True, False])

# Group job classifications and display top 5 skills for each
for classification in skill_counts_df['job_classification'].unique():
    print(f"Top 20 Skills for {classification}: \n")
    print(skill_counts_df[skill_counts_df['job_classification'] == classification].head(20))
    print("\n" + "-" * 80 + "\n")

Top 20 Skills for Cloud & Infrastructure Engineering:

                      job_classification              job_skills  count
820   Cloud & Infrastructure Engineering                  Python     17
1068  Cloud & Infrastructure Engineering         Troubleshooting     15
623   Cloud & Infrastructure Engineering                   Linux     10
227   Cloud & Infrastructure Engineering           Communication      9
174   Cloud & Infrastructure Engineering                 Cabling      8
706   Cloud & Infrastructure Engineering              Networking      8
295   Cloud & Infrastructure Engineering  Data Center Operations      7
1109  Cloud & Infrastructure Engineering                 Windows      6
97    Cloud & Infrastructure Engineering      Azure Data Factory      5
228   Cloud & Infrastructure Engineering    Communication Skills      5
591   Cloud & Infrastructure Engineering                    Java      5
890   Cloud & Infrastructure Engineering                     SQL      5
1047  Cloud & Infrastructure Engineering               Terraform      5
129   Cloud & Infrastructure Engineering                    Bash      4
135   Cloud & Infrastructure Engineering                Big Data      4
229   Cloud & Infrastructure Engineering    Communication skills      4
303   Cloud & Infrastructure Engineering        Data Engineering      4
348   Cloud & Infrastructure Engineering              Databricks      4
482   Cloud & Infrastructure Engineering                      Go      4
584   Cloud & Infrastructure Engineering    Inventory Management      4

--------------------------------------------------------------------------------

Top 20 Skills for Data Analyst:

      job_classification             job_skills  count
9640        Data Analyst                    SQL    723
3612        Data Analyst          Data Analysis    602
10595       Data Analyst                Tableau    462
8919        Data Analyst                 Python    458
4060        Data Analyst     Data Visualization    404
3096        Data Analyst          Communication    368
5283        Data Analyst                  Excel    284
9041        Data Analyst                      R    283
8440        Data Analyst               Power BI    272
4091        Data Analyst          Data analysis    268
10292       Data Analyst             Statistics    219
9302        Data Analyst              Reporting    211
4406        Data Analyst     Data visualization    201
3632        Data Analyst         Data Analytics    200
10685       Data Analyst               Teamwork    194
3859        Data Analyst            Data Mining    183
8562        Data Analyst        Problem Solving    168
2422        Data Analyst  Business Intelligence    158
8800        Data Analyst     Project Management    156
3835        Data Analyst        Data Management    152

--------------------------------------------------------------------------------

Top 20 Skills for Data Architect:

      job_classification         job_skills  count
14483     Data Architect                SQL    113
12459     Data Architect  Data Architecture     99
14268     Data Architect             Python     92
12605     Data Architect      Data Modeling     89
11662     Data Architect                AWS     74
12726     Data Architect   Data Warehousing     62
12532     Data Architect    Data Governance     57
12455     Data Architect     Data Architect     53
14616     Data Architect          Snowflake     51
12550     Data Architect   Data Integration     49
11894     Data Architect              Azure     47
12740     Data Architect  Data architecture     46
12293     Data Architect      Communication     44
12640     Data Architect       Data Quality     41
13450     Data Architect             Hadoop     41
12673     Data Architect      Data Security     40
13145     Data Architect                ETL     39
12585     Data Architect    Data Management     38
12831     Data Architect      Data modeling     38
13968     Data Architect              NoSQL     38

--------------------------------------------------------------------------------

Top 20 Skills for Data Engineer:

      job_classification        job_skills  count
21178      Data Engineer            Python    934
21590      Data Engineer               SQL    799
22038      Data Engineer             Spark    518
17457      Data Engineer  Data Engineering    493
19785      Data Engineer              Java    477
15504      Data Engineer               AWS    470
21718      Data Engineer             Scala    449
21920      Data Engineer         Snowflake    447
19379      Data Engineer            Hadoop    407
19818      Data Engineer             Kafka    380
21356      Data Engineer          Redshift    294
20487      Data Engineer             NoSQL    284
19476      Data Engineer              Hive    283
18692      Data Engineer               ETL    257
17861      Data Engineer  Data Warehousing    250
20419      Data Engineer             MySQL    242
15729      Data Engineer             Agile    233
18676      Data Engineer               EMR    217
15796      Data Engineer           Airflow    202
16646      Data Engineer         Cassandra    199

--------------------------------------------------------------------------------

Top 20 Skills for Data Governance & Security:

               job_classification          job_skills  count
23693  Data Governance & Security     Data Governance     93
25468  Data Governance & Security                 SQL     71
23452  Data Governance & Security       Communication     60
25302  Data Governance & Security              Python     51
23778  Data Governance & Security     Data Management     45
23813  Data Governance & Security        Data Privacy     45
23850  Data Governance & Security        Data Quality     44
23624  Data Governance & Security       Data Analysis     43
23890  Data Governance & Security       Data Security     43
25282  Data Governance & Security  Project Management     36
25733  Data Governance & Security             Tableau     36
23111  Data Governance & Security   Analytical Skills     34
23490  Data Governance & Security    Computer Science     32
23838  Data Governance & Security     Data Protection     31
25325  Data Governance & Security                   R     31
23966  Data Governance & Security     Data governance     28
23905  Data Governance & Security    Data Stewardship     26
24374  Data Governance & Security                 GIS     25
24367  Data Governance & Security                GDPR     24
23082  Data Governance & Security               Agile     23

--------------------------------------------------------------------------------

Top 20 Skills for Data Modeling & Warehousing:

                job_classification           job_skills  count
27024  Data Modeling & Warehousing                  SQL     64
26952  Data Modeling & Warehousing               Python     58
26702  Data Modeling & Warehousing                 JSON     55
26322  Data Modeling & Warehousing        Data Modeling     49
26963  Data Modeling & Warehousing                    R     44
27023  Data Modeling & Warehousing               SPARQL     42
26010  Data Modeling & Warehousing                 AVRO     39
26839  Data Modeling & Warehousing             Ontology     39
26061  Data Modeling & Warehousing  Amazon Web Services     37
26849  Data Modeling & Warehousing         OpenAPI/YAML     37
26834  Data Modeling & Warehousing                  OWL     36
26966  Data Modeling & Warehousing                  RDF     36
27022  Data Modeling & Warehousing                 SKOS     35
26433  Data Modeling & Warehousing           Data.World     34
26967  Data Modeling & Warehousing                 RDFS     34
27105  Data Modeling & Warehousing              Stardog     34
26075  Data Modeling & Warehousing            AnzoGraph     33
26813  Data Modeling & Warehousing              Neptune     33
26894  Data Modeling & Warehousing            PoolParty     33
26038  Data Modeling & Warehousing                Agile     32

--------------------------------------------------------------------------------

Top 20 Skills for Data Operations & Management:

                 job_classification              job_skills  count
27997  Data Operations & Management         Data Management     55
27916  Data Operations & Management           Data Analysis     46
29461  Data Operations & Management                     SQL     44
27772  Data Operations & Management           Communication     38
29294  Data Operations & Management                  Python     32
29263  Data Operations & Management      Project Management     26
29193  Data Operations & Management         Problem Solving     23
27757  Data Operations & Management           Collaboration     22
29750  Data Operations & Management                Teamwork     21
27445  Data Operations & Management     Attention to Detail     20
28097  Data Operations & Management      Data Visualization     19
29718  Data Operations & Management                 Tableau     19
28146  Data Operations & Management         Data management     18
28946  Data Operations & Management  Microsoft Office Suite     18
28067  Data Operations & Management           Data Security     17
29378  Data Operations & Management               Reporting     17
27979  Data Operations & Management         Data Governance     16
27983  Data Operations & Management        Data Integration     16
27774  Data Operations & Management    Communication Skills     15
28094  Data Operations & Management         Data Validation     15

--------------------------------------------------------------------------------

Top 20 Skills for Data Scientist:

      job_classification          job_skills  count
34193     Data Scientist              Python    513
34539     Data Scientist                 SQL    390
31514     Data Scientist        Data Science    350
33138     Data Scientist    Machine Learning    337
34247     Data Scientist                   R    310
34923     Data Scientist          Statistics    250
31576     Data Scientist  Data Visualization    173
31115     Data Scientist       Communication    155
35092     Data Scientist             Tableau    147
34796     Data Scientist               Spark    142
31377     Data Scientist       Data Analysis    129
33158     Data Scientist    Machine learning    117
31466     Data Scientist         Data Mining    103
30149     Data Scientist                 AWS    102
33267     Data Scientist         Mathematics    102
31176     Data Scientist    Computer Science     97
32575     Data Scientist              Hadoop     96
34187     Data Scientist             PyTorch     85
31382     Data Scientist      Data Analytics     84
32848     Data Scientist                Java     84

--------------------------------------------------------------------------------

Top 20 Skills for Data Specialist:

      job_classification              job_skills  count
36059    Data Specialist           Data Analysis     39
35944    Data Specialist           Communication     29
36113    Data Specialist         Data Management     29
36090    Data Specialist              Data Entry     28
36411    Data Specialist                   Excel     23
35777    Data Specialist     Attention to Detail     21
37205    Data Specialist                     SQL     19
36191    Data Specialist           Data analysis     18
36803    Data Specialist  Microsoft Office Suite     18
37409    Data Specialist                Teamwork     18
36846    Data Specialist            Multitasking     17
35947    Data Specialist    Communication skills     16
36983    Data Specialist         Problem Solving     15
37054    Data Specialist                  Python     14
37129    Data Specialist               Reporting     14
35933    Data Specialist           Collaboration     13
37022    Data Specialist      Project Management     13
36800    Data Specialist        Microsoft Office     12
35743    Data Specialist       Analytical Skills     11
35747    Data Specialist       Analytical skills     11

--------------------------------------------------------------------------------

Top 20 Skills for Database Engineer / Administrator:

                      job_classification               job_skills  count
42975  Database Engineer / Administrator                      SQL    263
41967  Database Engineer / Administrator                   Oracle    117
39520  Database Engineer / Administrator  Database Administration    116
43016  Database Engineer / Administrator               SQL Server    109
42584  Database Engineer / Administrator                   Python    107
41261  Database Engineer / Administrator                    Linux     78
44006  Database Engineer / Administrator          Troubleshooting     75
37725  Database Engineer / Administrator                      AWS     71
42359  Database Engineer / Administrator               PostgreSQL     69
39208  Database Engineer / Administrator            Data Modeling     68
38720  Database Engineer / Administrator            Communication     61
39769  Database Engineer / Administrator          Database design     59
41713  Database Engineer / Administrator                    MySQL     59
39566  Database Engineer / Administrator          Database Design     56
41117  Database Engineer / Administrator                     Java     56
42196  Database Engineer / Administrator                   PL/SQL     54
43832  Database Engineer / Administrator                 Teamwork     52
39416  Database Engineer / Administrator            Data modeling     51
41673  Database Engineer / Administrator                  MongoDB     51
42264  Database Engineer / Administrator       Performance Tuning     51

--------------------------------------------------------------------------------

Top 20 Skills for MLOps Engineer:

      job_classification              job_skills  count
45155     MLOps Engineer  Reinforcement Learning    112
45101     MLOps Engineer    Probabilistic Graphs    111
44919     MLOps Engineer                    LLMs    101
44812     MLOps Engineer             Flexibility    100
45036     MLOps Engineer                     NLP    100
45020     MLOps Engineer              Monitoring     98
44516     MLOps Engineer                Autonomy     96
44784     MLOps Engineer         Experimentation     74
44710     MLOps Engineer           Deep Learning     68
44944     MLOps Engineer                  ML Ops     68
44859     MLOps Engineer                  Hiring     65
44662     MLOps Engineer        Data Engineering     63
44760     MLOps Engineer             Engineering     58
45039     MLOps Engineer                NYCbased     57
44684     MLOps Engineer        Data engineering     53
45289     MLOps Engineer     Teamfirst mentality     53
45345     MLOps Engineer  Workflow Orchestration     52
45136     MLOps Engineer                  Python     51
45121     MLOps Engineer       Product ownership     49
45346     MLOps Engineer  Workflow orchestration     49

--------------------------------------------------------------------------------

Top 20 Skills for Machine Learning Engineer:

              job_classification           job_skills  count
47347  Machine Learning Engineer               Python    334
46809  Machine Learning Engineer     Machine Learning    286
47344  Machine Learning Engineer              PyTorch    199
47790  Machine Learning Engineer           TensorFlow    192
45507  Machine Learning Engineer                  AWS    137
46164  Machine Learning Engineer        Deep Learning    132
45643  Machine Learning Engineer                Azure    111
46614  Machine Learning Engineer                 Java    101
47143  Machine Learning Engineer               Pandas     88
46055  Machine Learning Engineer     Data Preparation     84
47519  Machine Learning Engineer                Scala     83
46625  Machine Learning Engineer              Jupyter     81
47061  Machine Learning Engineer                Numba     79
47793  Machine Learning Engineer           Tensorflow     78
45810  Machine Learning Engineer      Cloud Computing     75
46936  Machine Learning Engineer     Model Deployment     75
47639  Machine Learning Engineer                Spark     75
46644  Machine Learning Engineer           Kubernetes     74
46242  Machine Learning Engineer               Docker     72
46392  Machine Learning Engineer  Feature Engineering     70

--------------------------------------------------------------------------------

Top 20 Skills for Risk & Compliance Analytics:

                job_classification                            job_skills  \
48368  Risk & Compliance Analytics                                  CISM
48975  Risk & Compliance Analytics                                  JIRA
48370  Risk & Compliance Analytics                                 CISSP
48354  Risk & Compliance Analytics                                  CCSP
48366  Risk & Compliance Analytics                                  CISA
49424  Risk & Compliance Analytics                             Security+
48842  Risk & Compliance Analytics                                  GIAC
48112  Risk & Compliance Analytics                AWS Cloud Practitioner
48120  Risk & Compliance Analytics     AWS Solution Architect  Associate
48121  Risk & Compliance Analytics  AWS Solution Architect  Professional
48116  Risk & Compliance Analytics              AWS Developer  Associate
48118  Risk & Compliance Analytics               AWS Security  Specialty
49659  Risk & Compliance Analytics                        Virtualization
48558  Risk & Compliance Analytics                         Cybersecurity
48589  Risk & Compliance Analytics            Data Loss Prevention (DLP)
48638  Risk & Compliance Analytics                             Databases
48457  Risk & Compliance Analytics                         Communication
48107  Risk & Compliance Analytics                                   AWS
49397  Risk & Compliance Analytics                                  SaaS
49131  Risk & Compliance Analytics                           Network DLP

       count
48368     70
48975     69
48370     66
48354     62
48366     62
49424     62
48842     59
48112     58
48120     54
48121     54
48116     53
48118     53
49659     53
48558     51
48589     49
48638     45
48457     44
48107     40
49397     35
49131     34

--------------------------------------------------------------------------------

Top 20 Skills for Software & Platform Engineering:

                    job_classification            job_skills  count
51312  Software & Platform Engineering                Python    112
50849  Software & Platform Engineering                  Java     74
49767  Software & Platform Engineering                   AWS     67
51500  Software & Platform Engineering  Software Engineering     56
51424  Software & Platform Engineering                   SQL     54
50965  Software & Platform Engineering      Machine Learning     48
50875  Software & Platform Engineering            Kubernetes     41
51528  Software & Platform Engineering                 Spark     34
50518  Software & Platform Engineering                Docker     30
50862  Software & Platform Engineering                 Kafka     30
50038  Software & Platform Engineering                   C++     29
50157  Software & Platform Engineering         Communication     29
51518  Software & Platform Engineering  Software engineering     29
50076  Software & Platform Engineering       Cloud Computing     27
49934  Software & Platform Engineering                 Azure     26
50185  Software & Platform Engineering      Computer Science     25
51093  Software & Platform Engineering                 NoSQL     23
49862  Software & Platform Engineering            Algorithms     21
49887  Software & Platform Engineering          Apache Spark     21
50042  Software & Platform Engineering                 CI/CD     21


### **Normalize Skills**

In [30]:
# Skill Normalization by Ranking Priority
skill_normalization = {
    
    # Classification Control to limit clash of the multiple Skill Standardizations (Refer to Jose's Section)
    
    "bachelor's degree": r"(?i)\bbachelor's degree\b",
    "master's degree": r"(?i)\bmaster's degree\b",
    "phd": r"(?i)\bphd\b",
    "AWS Fundamentals": r"(?i)\bAWS Fundamentals\b",
    "AWS Developer Certifications": r"(?i)\bAWS Developer Certifications\b",
    "AWS Architecture Certifications": r"(?i)\bAWS Architecture Certifications\b",
    "AWS DevOps Certifications": r"(?i)\bAWS DevOps Certifications\b",
    "AWS SysOps Administrator": r"(?i)\bAWS SysOps Administrator\b",
    
    # Cloud & Infrastructure Engineering:
    
    "Troubleshooting": r"(?i)troubleshooting",
    "Linux": r"(?i)linux",
    "Communication": r"(?i)communication|communication\s+skills|comm|comms|communicate",
    "Cabling": r"(?i)cable[-\s]*ing",
    "Networking": r"(?i)networking",
    "Data Center Operations": r"(?i)data\s+center\s+operations",
    "Windows": r"(?i)windows",
    "Azure Data Factory": r"(?i)azure\s+data\s+factory|azuredatafactory",
    "Terraform": r"(?i)terraform",
    "Bash": r"(?i)(bash|shell|command\s+line|cli)",
    "Big Data": r"(?i)big\s+data|bigdata",
    "Data Engineering": r"(?i)data\s+engineering|dataeng|data\sengg|data\sengr",
    "Databricks": r"(?i)databricks",
    "Go": r"(?i)go|golang",
    "Inventory Management": r"(?i)inventory\s+management|inv\s+mgmt|inv\s+mgmnt",
    
    # Data Analyst:
    
    "Data Analysis": r"(?i)data\s*(analysis|analytics)|data\s*analyse",
    "Tableau": r"(?i)tableau",
    "Data Visualization": r"(?i)data\s+visualization|data\s+visualisation",
    "Excel": r"(?i)excel",
    "Power BI": r"(?i)power\s*bi",
    "Statistics": r"(?i)statistics|statistical",
    "Reporting": r"(?i)reporting|reports",
    "Teamwork": r"(?i)teamwork|collaboration|team-\s*first\s*mentality",
    "Data Mining": r"(?i)data\s+mining|mining",
    "Problem Solving": r"(?i)problem\s+solving|troubleshooting",
    "Business Intelligence": r"(?i)business\s*intelligence|bi",
    "Project Management": r"(?i)project\s*management",
    "Data Management": r"(?i)data\s+management",
    
    # Data Architect:
    
    "Data Architecture": r"(?i)data\s*(architecture|architect)",
    "Data Modeling": r"(?i)data\s*modeling|data\s*models|data\s*design",
    "Data Warehousing": r"(?i)data\s*warehousing|data\s*marts|dw",
    "Data Governance": r"(?i)data\s*governance|data\s*policy|data\s*compliance",
    "Snowflake": r"(?i)snowflake",
    "Data Integration": r"(?i)data\s*integration|etl|extract\s+transform\s+load|data\s*flow",
    "Data Quality": r"(?i)data\s*quality|dq",
    "Hadoop": r"(?i)hadoop",
    "Data Security": r"(?i)data\s*security|data\s*protection|cybersecurity",
    "ETL": r"(?i)etl|extract\s+transform\s+load|data\s*flow",
    "NoSQL": r"(?i)nosql",
    
    #Data Engineer:
    
    "Spark": r"(?i)spark|apache\s+spark",
    "Scala": r"(?i)scala",
    "Kafka": r"(?i)kafka|apache\s+kafka",
    "Redshift": r"(?i)redshift|amazon\s+redshift",
    "NoSQL": r"(?i)nosql",
    "Hive": r"(?i)hive|apache\s+hive",
    "ETL": r"(?i)etl|extract\s+transform\s+load",
    "MySQL": r"(?i)mysql",
    "Agile": r"(?i)agile",
    "EMR": r"(?i)emr|elastic\s+mapreduce|amazon\s+emr",
    "Airflow": r"(?i)airflow|apache\s+airflow",
    "Cassandra": r"(?i)cassandra|apache\s+cassandra",
    
    # Data Governance & Security:
    
    "Data Governance": r"(?i)data\s*governance|dg",
    "Data Privacy": r"(?i)data\s+privacy",
    "Analytical Skills": r"(?i)analytical\s+skills",
    "Computer Science": r"(?i)computer\s+science|cs",
    "Data Protection": r"(?i)data\s+protection|data\s*prot|dp",
    "Data Stewardship": r"(?i)data\s*stewardship",
    "GIS": r"(?i)gis|geographic\sinformation\s+systems",
    "GDPR": r"(?i)gdpr|general\+data\s+protection\s+regulation",
    
    # Data Modeling and Warehousing:
    
    "JSON": r"(?i)json",
    "SPARQL": r"(?i)sparql",
    "AVRO": r"(?i)avro",
    "Ontology": r"(?i)ontology",
    "OpenAPI/YAML": r"(?i)openapi/yaml",
    "OWL": r"(?i)owl",
    "SKOS": r"(?i)skos",
    "Data.World": r"(?i)data\.world",
    "RDFS": r"(?i)rdfs",
    "Stardog": r"(?i)stardog",
    "AnzoGraph": r"(?i)anzograph",
    "Neptune": r"(?i)neptune",
    "PoolParty": r"(?i)poolparty",
    
    # Data Operations & management: engineering
    
    'Collaboration': r"(?i)collaboration",
    'Attention to Detail': r"(?i)attention\s*to\s*detail",\
    'Microsoft Office Suite': r"(?i)microsoft\s*office(?:\ssuite)?",
    'Data Validation': r"(?i)data\s*validation",
    
    # Data Scientist:
    
    'Data Science': r"(?i)data\s*science",
    'Machine Learning': r"(?i)machine\s*learning|ml",
    'Mathematics': r"(?i)mathematics|maths",
    'PyTorch': r"(?i)pytorch",
    
    # Data Specialist:
    
    'Data Entry': r"(?i)data\s*entry",
    'Multitasking': r"(?i)multitasking",
    
    # Data Engineer / Administrator:
    
    'Oracle': r"(?i)oracle",
    'Database Administration': r"(?i)database\s*administration|db\sa|dba",
    'SQL Server': r"(?i)sql\s*server",
    'PostgreSQL': r"(?i)postgresql|postgres",
    'Database Design': r"(?i)database\sgesign|db\sdesign|database\sstructure",
    'PL/SQL': r"(?i)pl/sql",
    'MongoDB': r"(?i)(mongodb|mongo\s*database)",
    'Performance Tuning': r"(?i)performance\stuning|tuning",
    
    # ML Ops Engineer:
    
    'Reinforcement Learning': r"(?i)reinforcement\s*learning",
    'Probabilistic Graphs': r"(?i)probabilistic\s*graphs",
    'Flexibility': r"(?i)flexibility",
    'NLP': r"(?i)(nlp|natural\s*language\s*processing)",
    'Monitoring': r"(?i)monitoring",
    'Autonomy': r"(?i)autonomy",
    'Experimentation': r"(?i)experimentation",
    'Deep Learning': r"(?i)deep\s*learning",
    'ML Ops': r"(?i)(ml\s*ops|mlops|machine\s*learning\s*operations)",
    'Workflow Orchestration': r"(?i)workflow\s*orchestration",
    'Product Ownership': r"(?i)product\s*ownership",
    
    # Machine Learning Engineer:
    
    'TensorFlow': r"(?i)(tensorflow|tensor\s*flow)",
    'Pandas': r"(?i)pandas",
    'Data Preparation': r"(?i)data\s*preparation",
    'Jupyter': r"(?i)jupyter",
    'Numba': r"(?i)numba",
    "Cloud Computing": r"(?i)cloud\s+computing|cc",
    'Model Deployment': r"(?i)model\s*deployment",
    "Kubernetes": r"(?i)kubernetes|kube",
    'Docker': r"(?i)docker",
    'Feature Engineering': r"(?i)feature\s*engineering",
    
    # Risk and Compliance Analyst:
    
    'CISM': r"(?i)(certified\s*information\s*systems\s*manager|cism)",
    'JIRA': r"(?i)jira",
    'CISSP': r"(?i)(certified\s*information\s*systems\s*security\s*professional|cissp)",
    'CCSP': r"(?i)(certified\s*cloud\s*security\s*professional|ccsp)",
    'CISA': r"(?i)(certified\s*information\s*systems\s*auditor|cisa)",
    'Security+': r"(?i)(comp\.?\s*tia\ssecurity\+\s*certification|security\+)",
    'GIAC': r"(?i)giac",
    'AWS Cloud Practitioner': r"(?i)(aws\s*cloud\s*practitioner|awscp)",
    'AWS Solution Architect Associate': r"(?i)(aws\s*solution\s*architect\s*associate|aws\ssaa)",
    'AWS Solution Architect Professional': r"(?i)(aws\s*solution\s*architect\s*professional|aws\sasap)",
    'AWS Developer Associate': r"(?i)(aws\s*developer\s*associate|aws\sdaa)",
    'AWS Security Specialty': r"(?i)(aws\s*security\s*specialty|awsss)",
    'Virtualization': r"(?i)virtualization",
    'Cybersecurity': r"(?i)cybersecurity",
    'Data Loss Prevention (DLP)': r"(?i)(data\s*loss\s*prevention|dlp)",
    'Network DLP': r"(?i)(network\s*dlp|ndlp)",
    'SaaS': r"(?i)saas",
    
    # Software and Platform Engineering:
    
    "Software Engineering": r"(?i)software\s+engineering",
    "Kafka": r"(?i)kafka",
    "C++": r"(?i)c\+\+|\bCPLUSPLUS\b",
    "Algorithms": r"(?i)algorithms|algo",
    "CI/CD": r"(?i)ci/cd|continuous\s+integration/\s*continuous\s+deployment",
    "AI": r"(?i)ai|artificial\s+intelligence",
    
    # General / Added:
    
    'Engineering': r"(?i)engineering",
    'LLMs': r"(?i)(llms|large\s*language\s*models)",
    "Python": r"(?i)python(?:3(\.\d+)?)?|py",
    "RDF": r"(?i)rdf",
    "AWS": r"(?i)aws|amazon\s+web\sservices",
    "SQL": r"(?i)sql",
    "Azure": r"(?i)azure|microsft\s+azure",
    "Java": r"(?i)java|java\s+ee|java\s+se",
    "R": r"(?i)(?:^|[\s,])(r(?:\s+(?:programming|language|studio|basics|core|developer|development|statistical|stats|analysis))?)\b"
    
}

#### Skills to discuss
- Hiring (MLOPS)
- NYC-based (MLOPS)
- passion for vision (MLOPS)
- Team first mentality (MLOPS) --> TeamWork?

### **Classification Function**

In [31]:
# Function To Standardize top 20 Skills by Job Classification
def classify(skill):
    for skill_name, keyword in skill_normalization.items():
        if re.search(keyword, skill):
            return skill_name
    return skill

In [32]:
# Apply Regex to skill_breakdown Dataframe
skill_breakdown['cleaned_skills'] = skill_breakdown['job_skills'].apply(classify)

In [33]:
# Group by job_classification and count the number of skills
skill_counts_df = skill_breakdown.groupby(['job_classification', 'cleaned_skills']).size().reset_index(name='count')

# Sort values by job_classification and count in descending order
skill_counts_df = skill_counts_df.sort_values(['job_classification', 'count'], ascending=[True, False])

# Group job classifications and display top 5 skills for each
for classification in skill_counts_df['job_classification'].unique():
    print(f"Top 20 Skills for {classification}: \n")
    print(skill_counts_df[skill_counts_df['job_classification'] == classification].head(20))
    print("\n" + "-" * 80 + "\n")

Top 20 Skills for Cloud & Infrastructure Engineering:

                     job_classification          cleaned_skills  count
14   Cloud & Infrastructure Engineering                      AI     38
73   Cloud & Infrastructure Engineering   Business Intelligence     38
51   Cloud & Infrastructure Engineering                   Azure     37
784  Cloud & Infrastructure Engineering         Troubleshooting     36
219  Cloud & Infrastructure Engineering        Data Warehousing     35
134  Cloud & Infrastructure Engineering           Communication     34
141  Cloud & Infrastructure Engineering        Computer Science     25
291  Cloud & Infrastructure Engineering             Engineering     24
446  Cloud & Infrastructure Engineering                   Linux     21
588  Cloud & Infrastructure Engineering                  Python     18
58   Cloud & Infrastructure Engineering                    Bash     17
341  Cloud & Infrastructure Engineering                      Go     15
497  Cloud & Infrastructure Engineering              Networking     13
119  Cloud & Infrastructure Engineering         Cloud Computing     12
820  Cloud & Infrastructure Engineering                 Windows     10
190  Cloud & Infrastructure Engineering  Data Center Operations      9
91   Cloud & Infrastructure Engineering                 Cabling      8
201  Cloud & Infrastructure Engineering         Data Governance      8
233  Cloud & Infrastructure Engineering              Databricks      8
477  Cloud & Infrastructure Engineering              Monitoring      8

--------------------------------------------------------------------------------

Top 20 Skills for Data Analyst:

     job_classification         cleaned_skills  count
2370       Data Analyst          Data Analysis   1343
1948       Data Analyst          Communication    957
6854       Data Analyst                    SQL    838
1532       Data Analyst  Business Intelligence    799
2022       Data Analyst       Computer Science    772
7288       Data Analyst             Statistics    702
2702       Data Analyst     Data Visualization    685
6586       Data Analyst              Reporting    574
7497       Data Analyst                Tableau    523
6280       Data Analyst                 Python    514
3584       Data Analyst                  Excel    505
966        Data Analyst                     AI    490
5919       Data Analyst               Power BI    437
4042       Data Analyst                     Go    424
7563       Data Analyst               Teamwork    412
1868       Data Analyst        Cloud Computing    380
6382       Data Analyst                      R    329
2549       Data Analyst            Data Mining    303
2536       Data Analyst        Data Management    291
2514       Data Analyst       Data Integration    274

--------------------------------------------------------------------------------

Top 20 Skills for Data Architect:

      job_classification         cleaned_skills  count
8710      Data Architect      Data Architecture    250
8776      Data Architect       Data Integration    203
8813      Data Architect          Data Modeling    174
9405      Data Architect                     Go    160
8600      Data Architect          Communication    155
10209     Data Architect                    SQL    153
8454      Data Architect  Business Intelligence    150
8614      Data Architect       Computer Science    144
8313      Data Architect                    AWS    141
8410      Data Architect                  Azure    140
8301      Data Architect                     AI    127
8802      Data Architect        Data Management    111
8909      Data Architect       Data Warehousing    111
10032     Data Architect                 Python    100
8707      Data Architect          Data Analysis     97
9677      Data Architect       Machine Learning     93
8845      Data Architect           Data Quality     86
8860      Data Architect          Data Security     70
8751      Data Architect       Data Engineering     68
8330      Data Architect                  Agile     65

--------------------------------------------------------------------------------

Top 20 Skills for Data Engineer:

      job_classification         cleaned_skills  count
14458      Data Engineer                 Python   1022
14772      Data Engineer                    SQL   1018
15067      Data Engineer                  Spark    887
13129      Data Engineer                     Go    785
11223      Data Engineer  Business Intelligence    767
11900      Data Engineer       Data Integration    733
10882      Data Engineer                    AWS    726
11853      Data Engineer       Data Engineering    678
10917      Data Engineer                  Agile    648
12143      Data Engineer       Data Warehousing    593
11107      Data Engineer                  Azure    568
13498      Data Engineer                   Java    522
11594      Data Engineer       Computer Science    516
14818      Data Engineer                  Scala    497
14976      Data Engineer              Snowflake    482
13173      Data Engineer                 Hadoop    454
13952      Data Engineer                  NoSQL    451
13512      Data Engineer                  Kafka    435
11953      Data Engineer          Data Modeling    433
11551      Data Engineer          Communication    431

--------------------------------------------------------------------------------

Top 20 Skills for Data Governance & Security:

               job_classification         cleaned_skills  count
16666  Data Governance & Security                     Go    287
16063  Data Governance & Security          Communication    186
16312  Data Governance & Security          Data Security    161
16261  Data Governance & Security        Data Management    146
15942  Data Governance & Security  Business Intelligence    103
16291  Data Governance & Security           Data Quality    103
15804  Data Governance & Security                     AI    102
16179  Data Governance & Security          Data Analysis     98
17534  Data Governance & Security                    SQL     97
16283  Data Governance & Security           Data Privacy     93
16039  Data Governance & Security        Cloud Computing     92
16083  Data Governance & Security       Computer Science     88
17382  Data Governance & Security     Project Management     68
16242  Data Governance & Security       Data Integration     62
15824  Data Governance & Security                  Agile     58
17686  Data Governance & Security             Statistics     58
17394  Data Governance & Security                 Python     54
17757  Data Governance & Security               Teamwork     48
16234  Data Governance & Security        Data Governance     46
15833  Data Governance & Security      Analytical Skills     45

--------------------------------------------------------------------------------

Top 20 Skills for Data Modeling & Warehousing:

                job_classification         cleaned_skills  count
18059  Data Modeling & Warehousing       Computer Science     98
18049  Data Modeling & Warehousing          Communication     79
18611  Data Modeling & Warehousing                    SQL     79
18118  Data Modeling & Warehousing          Data Modeling     76
17954  Data Modeling & Warehousing                  Agile     72
17999  Data Modeling & Warehousing  Business Intelligence     68
18375  Data Modeling & Warehousing                   JSON     63
17949  Data Modeling & Warehousing                    AWS     62
18414  Data Modeling & Warehousing       Machine Learning     62
18547  Data Modeling & Warehousing                 Python     61
18108  Data Modeling & Warehousing       Data Integration     59
18469  Data Modeling & Warehousing               Ontology     56
18610  Data Modeling & Warehousing                 SPARQL     51
18537  Data Modeling & Warehousing     Project Management     46
18557  Data Modeling & Warehousing                      R     44
17943  Data Modeling & Warehousing                     AI     42
17948  Data Modeling & Warehousing                   AVRO     39
18472  Data Modeling & Warehousing           OpenAPI/YAML     37
18165  Data Modeling & Warehousing       Data Warehousing     36
18464  Data Modeling & Warehousing                    OWL     36

--------------------------------------------------------------------------------

Top 20 Skills for Data Operations & Management:

                 job_classification         cleaned_skills  count
19284  Data Operations & Management        Data Management    130
19108  Data Operations & Management          Communication    108
18990  Data Operations & Management  Business Intelligence     95
18961  Data Operations & Management                   Bash     90
19216  Data Operations & Management          Data Analysis     86
18830  Data Operations & Management                     AI     70
20344  Data Operations & Management              Reporting     67
19744  Data Operations & Management                     Go     58
19131  Data Operations & Management       Computer Science     54
20407  Data Operations & Management                    SQL     54
20632  Data Operations & Management               Teamwork     50
19077  Data Operations & Management        Cloud Computing     49
19314  Data Operations & Management           Data Quality     42
20272  Data Operations & Management                 Python     42
20529  Data Operations & Management             Statistics     41
19271  Data Operations & Management       Data Integration     38
19649  Data Operations & Management                  Excel     38
20247  Data Operations & Management     Project Management     36
19608  Data Operations & Management            Engineering     34
18909  Data Operations & Management    Attention to Detail     28

--------------------------------------------------------------------------------

Top 20 Skills for Data Scientist:

      job_classification         cleaned_skills  count
21471     Data Scientist       Computer Science    745
24146     Data Scientist             Statistics    672
22869     Data Scientist       Machine Learning    651
23628     Data Scientist                 Python    596
21729     Data Scientist           Data Science    501
23898     Data Scientist                    SQL    403
20908     Data Scientist                     AI    390
21428     Data Scientist          Communication    381
21619     Data Scientist          Data Analysis    360
23673     Data Scientist                      R    328
21204     Data Scientist  Business Intelligence    311
22400     Data Scientist                     Go    275
21753     Data Scientist     Data Visualization    263
24107     Data Scientist                  Spark    189
24299     Data Scientist               Teamwork    171
24272     Data Scientist                Tableau    169
23109     Data Scientist                    NLP    163
21691     Data Scientist            Data Mining    156
20925     Data Scientist                    AWS    151
21348     Data Scientist        Cloud Computing    108

--------------------------------------------------------------------------------

Top 20 Skills for Data Specialist:

      job_classification          cleaned_skills  count
24786    Data Specialist   Business Intelligence    131
24841    Data Specialist           Communication    105
24931    Data Specialist           Data Analysis     77
24695    Data Specialist                      AI     60
24775    Data Specialist                    Bash     53
24831    Data Specialist         Cloud Computing     52
25746    Data Specialist               Reporting     50
24956    Data Specialist              Data Entry     46
24972    Data Specialist         Data Management     45
25968    Data Specialist                Teamwork     45
24991    Data Specialist            Data Quality     44
25192    Data Specialist                   Excel     44
24852    Data Specialist        Computer Science     43
25257    Data Specialist                      Go     35
25479    Data Specialist  Microsoft Office Suite     35
24754    Data Specialist     Attention to Detail     31
25622    Data Specialist         Problem Solving     25
24734    Data Specialist       Analytical Skills     23
25654    Data Specialist      Project Management     23
25805    Data Specialist                     SQL     23

--------------------------------------------------------------------------------

Top 20 Skills for Database Engineer / Administrator:

                      job_classification           cleaned_skills  count
29787  Database Engineer / Administrator                      SQL    484
29164  Database Engineer / Administrator                   Oracle    402
26776  Database Engineer / Administrator            Communication    309
26540  Database Engineer / Administrator    Business Intelligence    302
26185  Database Engineer / Administrator                       AI    300
29788  Database Engineer / Administrator               SQL Server    274
27370  Database Engineer / Administrator  Database Administration    241
26816  Database Engineer / Administrator         Computer Science    233
28234  Database Engineer / Administrator                       Go    198
29241  Database Engineer / Administrator       Performance Tuning    184
27141  Database Engineer / Administrator            Data Modeling    176
26507  Database Engineer / Administrator                     Bash    167
27117  Database Engineer / Administrator         Data Integration    164
26207  Database Engineer / Administrator                      AWS    148
26694  Database Engineer / Administrator          Cloud Computing    137
28687  Database Engineer / Administrator                    Linux    135
27052  Database Engineer / Administrator            Data Analysis    126
29315  Database Engineer / Administrator               PostgreSQL    125
26407  Database Engineer / Administrator                    Azure    116
29475  Database Engineer / Administrator                   Python    114

--------------------------------------------------------------------------------

Top 20 Skills for MLOps Engineer:

      job_classification          cleaned_skills  count
31067     MLOps Engineer        Machine Learning    351
30827     MLOps Engineer   Business Intelligence    312
30883     MLOps Engineer        Data Engineering    122
31171     MLOps Engineer  Reinforcement Learning    118
30917     MLOps Engineer           Deep Learning    117
31089     MLOps Engineer                     NLP    117
31082     MLOps Engineer              Monitoring    114
30885     MLOps Engineer        Data Integration    113
31057     MLOps Engineer                    LLMs    111
30810     MLOps Engineer                Autonomy    104
31315     MLOps Engineer  Workflow Orchestration    101
31145     MLOps Engineer       Product Ownership     96
30957     MLOps Engineer         Experimentation     91
30947     MLOps Engineer             Engineering     84
31157     MLOps Engineer                  Python     71
31008     MLOps Engineer                  Hiring     65
31091     MLOps Engineer                NYCbased     57
31272     MLOps Engineer     Teamfirst mentality     53
30788     MLOps Engineer                      AI     48
30786     MLOps Engineer             A/B Testing     47

--------------------------------------------------------------------------------

Top 20 Skills for Machine Learning Engineer:

              job_classification         cleaned_skills  count
32186  Machine Learning Engineer       Machine Learning    751
32533  Machine Learning Engineer                 Python    450
31380  Machine Learning Engineer                     AI    340
32874  Machine Learning Engineer             TensorFlow    275
32532  Machine Learning Engineer                PyTorch    212
31995  Machine Learning Engineer                     Go    199
31403  Machine Learning Engineer                  Agile    194
31386  Machine Learning Engineer                    AWS    190
31789  Machine Learning Engineer          Deep Learning    187
31567  Machine Learning Engineer          Communication    149
31479  Machine Learning Engineer  Business Intelligence    142
31586  Machine Learning Engineer       Computer Science    141
31450  Machine Learning Engineer                  Azure    120
32102  Machine Learning Engineer                   Java    112
32759  Machine Learning Engineer                  Spark    106
32669  Machine Learning Engineer                  Scala     99
32307  Machine Learning Engineer                    NLP     97
31703  Machine Learning Engineer       Data Preparation     95
31524  Machine Learning Engineer        Cloud Computing     93
32114  Machine Learning Engineer             Kubernetes     90

--------------------------------------------------------------------------------

Top 20 Skills for Risk & Compliance Analytics:

                job_classification                       cleaned_skills  count
33386  Risk & Compliance Analytics           Data Loss Prevention (DLP)    198
33394  Risk & Compliance Analytics                        Data Security    175
33290  Risk & Compliance Analytics                        Communication    116
33727  Risk & Compliance Analytics                     Machine Learning    114
33299  Risk & Compliance Analytics                     Computer Science    109
33091  Risk & Compliance Analytics                                Agile    103
33275  Risk & Compliance Analytics                      Cloud Computing    100
33683  Risk & Compliance Analytics                                 JIRA     92
33075  Risk & Compliance Analytics                                   AI     77
33230  Risk & Compliance Analytics                                 CISM     75
33077  Risk & Compliance Analytics                                  AWS     69
33232  Risk & Compliance Analytics                                CISSP     68
33078  Risk & Compliance Analytics               AWS Cloud Practitioner     63
33229  Risk & Compliance Analytics                                 CISA     63
34037  Risk & Compliance Analytics                            Security+     62
33566  Risk & Compliance Analytics                                 GIAC     59
33081  Risk & Compliance Analytics     AWS Solution Architect Associate     54
33082  Risk & Compliance Analytics  AWS Solution Architect Professional     54
33961  Risk & Compliance Analytics                            Reporting     54
34224  Risk & Compliance Analytics                       Virtualization     54

--------------------------------------------------------------------------------

Top 20 Skills for Software & Platform Engineering:

                    job_classification         cleaned_skills  count
34295  Software & Platform Engineering                    AWS    131
35319  Software & Platform Engineering                 Python    127
35073  Software & Platform Engineering       Machine Learning    124
34282  Software & Platform Engineering                     AI    116
34906  Software & Platform Engineering                     Go    111
34399  Software & Platform Engineering  Business Intelligence    105
34513  Software & Platform Engineering       Computer Science    104
35013  Software & Platform Engineering                   Java     99
35473  Software & Platform Engineering   Software Engineering     95
34305  Software & Platform Engineering                  Agile     85
34495  Software & Platform Engineering          Communication     79
35495  Software & Platform Engineering                  Spark     73
35414  Software & Platform Engineering                    SQL     69
34435  Software & Platform Engineering        Cloud Computing     59
34361  Software & Platform Engineering                  Azure     44
35017  Software & Platform Engineering                  Kafka     44
34661  Software & Platform Engineering       Data Warehousing     42

### **Create skill_counts_df and Group by job_keyword**

In [34]:
# Group by job_keyword and count the number of skills
skill_keyword_counts_df = skill_breakdown.groupby(['job_keyword', 'job_skills']).size().reset_index(name='count')

# Sort values by job_keyword and count in descending order
skill_keyword_counts_df = skill_keyword_counts_df.sort_values(['job_keyword', 'count'], ascending=[True, False])

# Group job_keyword and display top 5 skills for each
for keyword in skill_keyword_counts_df['job_keyword'].unique():
    print(f"Top 5 Skills for {keyword}: \n")
    print(skill_keyword_counts_df[skill_keyword_counts_df['job_keyword'] == keyword].head())
    print("\n" + "-" * 80 + "\n")

Top 5 Skills for Ai Data Science Lead:

            job_keyword          job_skills  count
0  Ai Data Science Lead                  AI      1
1  Ai Data Science Lead                 AWS      1
2  Ai Data Science Lead  Agile Applications      1
3  Ai Data Science Lead                 CNN      1
4  Ai Data Science Lead      Classification      1

--------------------------------------------------------------------------------

Top 5 Skills for Aml:

    job_keyword        job_skills  count
220         Aml     Communication     18
60          Aml               AML     10
565         Aml            Python      9
610         Aml               SQL      9
441         Aml  Machine Learning      8

--------------------------------------------------------------------------------

Top 5 Skills for Application Developer:

               job_keyword                            job_skills  count
733  Application Developer              Contact Center Operation      1
734  Application Developer  Cross System Communication Protocols      1
735  Application Developer      Dissimilar SIP Telephony Systems      1
736  Application Developer                              Grammars      1
737  Application Developer           IVR Application Development      1

--------------------------------------------------------------------------------

Top 5 Skills for Aws Databricks:

        job_keyword        job_skills  count
751  Aws Databricks               AWS      1
752  Aws Databricks       Apache NiFi      1
753  Aws Databricks     Communication      1
754  Aws Databricks    Data Analytics      1
755  Aws Databricks  Data Engineering      1

--------------------------------------------------------------------------------

Top 5 Skills for Azure Data:

    job_keyword          job_skills  count
798  Azure Data  Azure Data Factory      5
924  Azure Data              Python      4
802  Azure Data    Azure Databricks      3
809  Azure Data       Azure Synapse      3
848  Azure Data       Data Modeling      3

--------------------------------------------------------------------------------

Top 5 Skills for Azure Databricks:

          job_keyword                             job_skills  count
966  Azure Databricks                           Apache Spark      1
967  Azure Databricks                                  Azure      1
968  Azure Databricks       Cloud Data Bricks Infrastructure      1
969  Azure Databricks                  Cloud native services      1
970  Azure Databricks  Data bricks Data Engineering platform      1

--------------------------------------------------------------------------------

Top 5 Skills for Backend Engineer:

           job_keyword             job_skills  count
1029  Backend Engineer                 Python      2
984   Backend Engineer  AI company experience      1
985   Backend Engineer      Agile Development      1
986   Backend Engineer                Airflow      1
987   Backend Engineer             Automation      1

--------------------------------------------------------------------------------

Top 5 Skills for Bi Analyst:

     job_keyword                           job_skills  count
1054  Bi Analyst                        Communication      2
1068  Bi Analyst                   Data visualization      2
1090  Bi Analyst                             Power BI      2
1102  Bi Analyst                                  SQL      2
1045  Bi Analyst  Abstract Analytical Problem Solving      1

--------------------------------------------------------------------------------

Top 5 Skills for Big Data Architect:

             job_keyword job_skills  count
1209  Big Data Architect     Python      5
1218  Big Data Architect      Spark      5
1213  Big Data Architect        SQL      4
1179  Big Data Architect     Hadoop      3
1113  Big Data Architect  AWS Cloud      2

--------------------------------------------------------------------------------

Top 5 Skills for Big Data Developer:

             job_keyword job_skills  count
1338  Big Data Developer     Hadoop      6
1412  Big Data Developer      Spark      6
1343  Big Data Developer       Hive      4
1388  Big Data Developer     Python      4
1305  Big Data Developer     DevOps      3

--------------------------------------------------------------------------------

Top 5 Skills for Big Data Engineer:

            job_keyword job_skills  count
1716  Big Data Engineer     Python     16
1733  Big Data Engineer        SQL     15
1659  Big Data Engineer       Java     12
1751  Big Data Engineer      Spark     12
1735  Big Data Engineer      Scala      9

--------------------------------------------------------------------------------

Top 5 Skills for Big Data Engineering:

               job_keyword              job_skills  count
1788  Big Data Engineering                     AWS      1
1789  Big Data Engineering  Building Data pipeline      1
1790  Big Data Engineering         Data publishing      1
1791  Big Data Engineering           Data sourcing      1
1792  Big Data Engineering                Database      1

--------------------------------------------------------------------------------

Top 5 Skills for Bsa:

     job_keyword     job_skills  count
1883         Bsa        BSA/AML     12
1977         Bsa  Communication     11
2115         Bsa          Fraud     11
2220         Bsa           OFAC     11
1982         Bsa     Compliance     10

--------------------------------------------------------------------------------

Top 5 Skills for Business Intelligence:

                job_keyword             job_skills  count
2591  Business Intelligence     Data Visualization     16
2905  Business Intelligence                    SQL     15
2477  Business Intelligence  Business Intelligence     14
2820  Business Intelligence               Power BI     14
2502  Business Intelligence          Communication     12

--------------------------------------------------------------------------------

Top 5 Skills for Cloud Data:

     job_keyword            job_skills  count
3002  Cloud Data                Amazon      2
3003  Cloud Data             Analytics      2
3020  Cloud Data       Cloud Computing      2
3025  Cloud Data  Communication Skills      2
3029  Cloud Data     Data Architecture      2

--------------------------------------------------------------------------------

Top 5 Skills for Cloud Data Architect:

               job_keyword            job_skills  count
3113  Cloud Data Architect                 Azure      4
3163  Cloud Data Architect          Data Quality      3
3186  Cloud Data Architect                   ETL      3
3104  Cloud Data Architect                   AWS      2
3132  Cloud Data Architect  Cloud Data Architect      2

--------------------------------------------------------------------------------

Top 5 Skills for Cloud Database:

         job_keyword   job_skills  count
3437  Cloud Database   PostgreSQL      7
3267  Cloud Database          AWS      4
3293  Cloud Database    Bitbucket      4
3457  Cloud Database          SQL      4
3282  Cloud Database  Artifactory      3

--------------------------------------------------------------------------------

Top 5 Skills for Cloud Datawarehouse:

              job_keyword                             job_skills  count
3492  Cloud Datawarehouse                              401K Plan      1
3493  Cloud Datawarehouse                                    AWS      1
3494  Cloud Datawarehouse       AWS Certified Cloud Practitioner      1
3495  Cloud Datawarehouse  AWS Certified Data AnalyticsSpecialty      1
3496  Cloud Datawarehouse        AWS Certified DatabaseSpecialty      1

--------------------------------------------------------------------------------

Top 5 Skills for Cloud Engineer:

         job_keyword                 job_skills  count
3545  Cloud Engineer  AWS Fargate (EKS Fargate)      1
3546  Cloud Engineer                       CMTS      1
3547  Cloud Engineer                    Datadog      1
3548  Cloud Engineer                    Grafana      1
3549  Cloud Engineer                     Modems      1

--------------------------------------------------------------------------------

Top 5 Skills for Data Analyst:

        job_keyword          job_skills  count
11620  Data Analyst                 SQL    686
5892   Data Analyst       Data Analysis    574
12529  Data Analyst             Tableau    447
10928  Data Analyst              Python    443
6312   Data Analyst  Data Visualization    379

--------------------------------------------------------------------------------

Top 5 Skills for Data Analystat:

          job_keyword               job_skills  count
13498  Data Analystat  Artificial Intelligence      1
13499  Data Analystat  Biometric Data Analysis      1
13500  Data Analystat               Blockchain      1
13501  Data Analystat             Data Privacy      1
13502  Data Analystat            Data Security      1

--------------------------------------------------------------------------------

Top 5 Skills for Data Analystics:

           job_keyword               job_skills  count
13513  Data Analystics        Agile Development      1
13514  Data Analystics      Analytical Thinking      1
13515  Data Analystics  Artificial Intelligence      1
13516  Data Analystics                    Azure      1
13517  Data Analystics                Budgeting      1

--------------------------------------------------------------------------------

Top 5 Skills for Data Analysts:

         job_keyword     job_skills  count
13596  Data Analysts  Data Analysis      4
13616  Data Analysts        Degreed      3
13623  Data Analysts     Eagle PACE      3
13624  Data Analysts     Eagle STAR      3
13628  Data Analysts          Excel      3

--------------------------------------------------------------------------------

Top 5 Skills for Data Architect:

          job_keyword         job_skills  count
16010  Data Architect                SQL     77
14392  Data Architect  Data Architecture     73
15834  Data Architect             Python     68
14505  Data Architect      Data Modeling     63
13742  Data Architect                AWS     48

--------------------------------------------------------------------------------

Top 5 Skills for Data Architecture:

             job_keyword         job_skills  count
16529  Data Architecture                AWS     13
16691  Data Architecture             Python     11
16712  Data Architecture                SQL     10
16715  Data Architecture              Scala     10
16588  Data Architecture  Data Architecture      7

--------------------------------------------------------------------------------

Top 5 Skills for Data Business Analyst:

                 job_keyword           job_skills  count
16854  Data Business Analyst                  SQL      3
16763  Data Business Analyst    Analytical Skills      2
16790  Data Business Analyst        Data Analysis      2
16792  Data Business Analyst      Data Governance      2
16793  Data Business Analyst  Data Interpretation      2

--------------------------------------------------------------------------------

Top 5 Skills for Data Compliance:

           job_keyword           job_skills  count
16872  Data Compliance    Analytical skills      1
16873  Data Compliance  Attention to detail      1
16874  Data Compliance        Collaboration      1
16875  Data Compliance    Compliance Review      1
16876  Data Compliance  Contract Management      1

--------------------------------------------------------------------------------

Top 5 Skills for Data Consultant:

           job_keyword       job_skills  count
17208  Data Consultant              SQL      7
16976  Data Consultant    Data Analysis      5
17152  Data Consultant           Oracle      5
16896  Data Consultant     Adaptability      4
16999  Data Consultant  Data Management      4

--------------------------------------------------------------------------------

Top 5 Skills for Data Conversion:

           job_keyword        job_skills  count
17281  Data Conversion    Data Cleansing      2
17282  Data Conversion   Data Conversion      2
17284  Data Conversion  Data Integration      2
17287  Data Conversion   Data Validation      2
17316  Data Conversion   Time Management      2

--------------------------------------------------------------------------------

Top 5 Skills for Data Coordinator:

            job_keyword         job_skills  count
17356  Data Coordinator      Communication      6
17379  Data Coordinator      Data Analysis      6
17437  Data Coordinator              Excel      5
17578  Data Coordinator           Teamwork      5
17342  Data Coordinator  Bachelor's Degree      4

--------------------------------------------------------------------------------

Top 5 Skills for Data Engineer:

         job_keyword        job_skills  count
21329  Data Engineer            Python    375
21598  Data Engineer               SQL    348
19025  Data Engineer  Data Engineering    200
17792  Data Engineer               AWS    165
20479  Data Engineer              Java    148

--------------------------------------------------------------------------------

Top 5 Skills for Data Engineering:

            job_keyword        job_skills  count
23825  Data Engineering            Python    147
23902  Data Engineering               SQL    103
22542  Data Engineering               AWS    100
22988  Data Engineering  Data Engineering     95
23920  Data Engineering             Scala     93

--------------------------------------------------------------------------------

Top 5 Skills for Data Engineers:

          job_keyword          job_skills  count
24179  Data Engineers          Algorithms      2
24178  Data Engineers                 AWS      1
24180  Data Engineers  Analytical Mindset      1
24181  Data Engineers    Analytical Tools      1
24182  Data Engineers      Apache Airflow      1

--------------------------------------------------------------------------------

Top 5 Skills for Data Entry Specialist:

                 job_keyword              job_skills  count
24309  Data Entry Specialist              Data Entry     18
24253  Data Entry Specialist     Attention to Detail     12
24297  Data Entry Specialist        Customer Service      5
24399  Data Entry Specialist  Microsoft Office Suite      5
24359  Data Entry Specialist                     GLP      4

--------------------------------------------------------------------------------

Top 5 Skills for Data Governance:

           job_keyword       job_skills  count
24768  Data Governance  Data Governance     43
24677  Data Governance    Communication     26
25467  Data Governance              SQL     22
24870  Data Governance     Data Quality     21
24937  Data Governance  Data governance     19

--------------------------------------------------------------------------------

Top 5 Skills for Data Infrastructure:

               job_keyword           job_skills  count
25769  Data Infrastructure           Kubernetes     12
25712  Data Infrastructure               Docker     11
25882  Data Infrastructure            Terraform     10
25680  Data Infrastructure     Data Engineering      8
25683  Data Infrastructure  Data Infrastructure      8

--------------------------------------------------------------------------------

Top 5 Skills for Data Integrations:

             job_keyword                     job_skills  count
25894  Data Integrations              Analytical Skills      1
25895  Data Integrations            Appointment Setting      1
25896  Data Integrations  B2B Software Sales Experience      1
25897  Data Integrations              Bachelor's degree      1
25898  Data Integrations                       Big Data      1

--------------------------------------------------------------------------------

Top 5 Skills for Data Lake Architect:

               job_keyword     job_skills  count
25941  Data Lake Architect          Azure      2
25949  Data Lake Architect  Data Security      2
25959  Data Lake Architect         DevOps      2
25960  Data Lake Architect            ETL      2
25964  Data Lake Architect         Hadoop      2

--------------------------------------------------------------------------------

Top 5 Skills for Data Lifecycle Manager:

                  job_keyword                          job_skills  count
25983  Data Lifecycle Manager                                 AWS      3
25984  Data Lifecycle Manager                    Active Directory      3
25986  Data Lifecycle Manager                               Azure      3
26005  Data Lifecycle Manager  Microsoft Distributed File Systems      3
26027  Data Lifecycle Manager                   Windows File ACLs      3

--------------------------------------------------------------------------------

Top 5 Skills for Data Loss Prevention:

                job_keyword job_skills  count
26329  Data Loss Prevention       JIRA     67
26139  Data Loss Prevention      CISSP     65
26138  Data Loss Prevention       CISM     63
26135  Data Loss Prevention       CCSP     62
26437  Data Loss Prevention  Security+     62

--------------------------------------------------------------------------------

Top 5 Skills for Data Management Engineer:

                    job_keyword  \
26548  Data Management Engineer
26535  Data Management Engineer
26536  Data Management Engineer
26537  Data Management Engineer
26538  Data Management Engineer

                                              job_skills  count
26548                                    Data Management      2
26535  5+ years of Configuration or Data Management E...      1
26536                 7+ years of Engineering Experience      1
26537                                              Agile      1
26538                                            Agility      1

--------------------------------------------------------------------------------

Top 5 Skills for Data Manager:

        job_keyword          job_skills  count
27067  Data Manager     Data Management     43
27006  Data Manager       Data Analysis     36
26908  Data Manager       Communication     25
28113  Data Manager                 SQL     24
27968  Data Manager  Project Management     18

--------------------------------------------------------------------------------

Top 5 Skills for Data Modeling:

         job_keyword job_skills  count
28793  Data Modeling       JSON     55
28917  Data Modeling     Python     48
28946  Data Modeling        SQL     46
28922  Data Modeling          R     43
28945  Data Modeling     SPARQL     42

--------------------------------------------------------------------------------

Top 5 Skills for Data Operations:

           job_keyword           job_skills  count
29551  Data Operations                  SQL     13
29517  Data Operations               Python     12
29181  Data Operations        Communication     11
29253  Data Operations      Data Operations     11
29097  Data Operations  Attention to Detail      9

--------------------------------------------------------------------------------

Top 5 Skills for Data Pipeline Engineer:

                  job_keyword                 job_skills  count
29661  Data Pipeline Engineer          Data Architecture      1
29662  Data Pipeline Engineer  Data Pipeline Engineering      1
29663  Data Pipeline Engineer                    FastAPI      1
29664  Data Pipeline Engineer                      Figma      1
29665  Data Pipeline Engineer   Inline Measurement Tools      1

--------------------------------------------------------------------------------

Top 5 Skills for Data Privacy:

        job_keyword       job_skills  count
29858  Data Privacy     Data Privacy     26
29880  Data Privacy  Data Protection     14
29960  Data Privacy             GDPR     13
29739  Data Privacy             CCPA     11
29788  Data Privacy    Communication     11

--------------------------------------------------------------------------------

Top 5 Skills for Data Processing:
